version: "3"

services:
  app:
    build: .
    image: app
    env_file: .env
    restart: always
    command: ["python", "app.py", "--debug"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - postgres

  worker:
    build: .
    image: app
    restart: always
    env_file: .env
    volumes:
      - ./app:/app
    command:
      [
        "celery",
        "worker",
        "--app=worker.app",
        "--concurrency=1",
        "--loglevel=INFO",
      ]
    depends_on:
      - postgres

  migrations:
    build: .
    image: app
    restart: "no"
    env_file: .env
    volumes:
      - ./app:/app
    command: ["alembic", "upgrade", "head"]
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-alpine
    env_file: .env
    hostname: "myrabbit"
    ports:
      - 5672:5672

  postgres:
    image: postgres:11-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
