"""init

Revision ID: 693e89f6d6ed
Revises: c933a006fd78
Create Date: 2019-02-20 15:00:30.372089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693e89f6d6ed'
down_revision = 'c933a006fd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
