"""init

Revision ID: c933a006fd78
Revises: 
Create Date: 2019-02-20 14:56:41.900322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c933a006fd78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('secid', sa.String(length=36), nullable=False),
    sa.Column('tradedate', sa.Date(), nullable=False),
    sa.Column('group', sa.String(length=120), nullable=True),
    sa.Column('assetcode', sa.String(length=10), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('secid', 'tradedate')
    )
    op.create_index(op.f('ix_history_group'), 'history', ['group'], unique=False)
    op.create_index(op.f('ix_history_secid'), 'history', ['secid'], unique=False)
    op.create_index(op.f('ix_history_tradedate'), 'history', ['tradedate'], unique=False)
    op.create_table('securities',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('secid', sa.String(length=36), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    op.drop_index(op.f('ix_history_tradedate'), table_name='history')
    op.drop_index(op.f('ix_history_secid'), table_name='history')
    op.drop_index(op.f('ix_history_group'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
